version: '3.1'
services:
  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}-nginx
    working_dir: /var/www/application
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80

  php-fpm:
    build: ./docker/php/
    container_name: ${PROJECT_NAME}-php
    working_dir: /var/www/application
    volumes:
      - ./:/var/www/application
